const {test}=require('node:test');
const assert=require('node:assert/strict');
const {identificarMateria}=require('../identificar-materia');
const {chromium}=require('playwright');
const {criarPainelManual}=require('../painel-manual');
const exemplo = '**MATÉRIA 4 DE 15**\n\n**CHAPÉU:** RADAR CLIMA E TEMPO\n\n## Rio Largo tem possibilidade de chuva e máxima prevista de 28°C\n\n### Céu varia entre muitas nuvens e períodos de abertura; mínima fica próxima de 22°C\n\n**Rio Largo** — Rio Largo deve registrar temperaturas entre 22°C e 28°C nesta quarta-feira (9), com possibilidade de chuva e variação de nebulosidade.\n\nA chuva, se ocorrer, tende a ser passageira e localizada.\n\n#### Previsão por faixa horária\n\n| 6h | 9h |\n| --- | --- |\n| 22°C • nublado | 23°C • chuva possível |\n\n*A grade horária é uma estimativa editorial.*\n\n#### DADOS PARA O CMS\n\n**Título:** Rio Largo tem possibilidade de chuva e máxima prevista de 28°C\\\n**Subtítulo:** Céu varia entre muitas nuvens e períodos de abertura; mínima fica próxima de 22°C\\\n**Slug:** rio-largo\\\n**Tags:** Rio Largo, chuva\n\n#### TRANSPARÊNCIA\n\nTexto elaborado em 9 de setembro de 2026.\n\n**Fontes:** [INMET](https://previsao.inmet.gov.br/).';
test('separa o exemplo, preserva corpo/tabela/fontes e usa a hora atual de Brasília',()=>{
 const {campos:c,origem}=identificarMateria(exemplo,new Date('2026-09-10T01:25:36Z'));
 assert.equal(c.categoria,'Clima e Tempo'); assert.match(origem.categoria,/Sugestão/);
 assert.equal(c.data,'2026-09-09T22:25:36');
 assert.equal(c.titulo,'Rio Largo tem possibilidade de chuva e máxima prevista de 28°C');
 assert.equal(c.bigode,'Céu varia entre muitas nuvens e períodos de abertura; mínima fica próxima de 22°C');
 assert.equal(c.chapeu,'RADAR CLIMA E TEMPO'); assert.equal(c.autor,''); assert.equal(c.imagem,'');
 assert.match(c.redacao,/^\*\*Rio Largo\*\* —/); assert.match(c.redacao,/\| 22°C • nublado/); assert.match(c.redacao,/TRANSPARÊNCIA/); assert.match(c.redacao,/https:\/\/previsao.inmet.gov.br/);
 assert.doesNotMatch(c.redacao,/DADOS PARA O CMS|\*\*Título:|\*\*Tags:|MATÉRIA 4 DE 15|## Rio Largo/);
});
test('rótulos explícitos têm prioridade; a data recebida não substitui a atual',()=>{
 const {campos:c}=identificarMateria('Categoria: RJ em Foco\nTítulo: Chuva no Rio\nChapéu: CIDADE\nBigode: Alerta local\nAutor: Ana Souza\nData: 01/01/2000\nImagem destaque: https://exemplo.test/foto.jpg\nRedação: Primeiro parágrafo.\n\nSegundo parágrafo.');
 assert.equal(c.categoria,'RJ em Foco');assert.equal(c.autor,'Ana Souza');assert.equal(c.imagem,'https://exemplo.test/foto.jpg');assert.equal(c.redacao,'Primeiro parágrafo.\n\nSegundo parágrafo.');assert.ok(!c.data.startsWith('2000'));
});
test('texto simples sugere primeira linha e mantém campos desconhecidos vazios',()=>{
 const {campos:c,origem}=identificarMateria('Encontro reúne moradores\n\nPor Ana Souza\n\nOs moradores participaram do evento.');
 assert.equal(c.titulo,'Encontro reúne moradores');assert.match(origem.titulo,/Sugestão/);assert.equal(c.autor,'Ana Souza');assert.equal(c.categoria,'');assert.equal(c.bigode,'');assert.equal(c.redacao,'Os moradores participaram do evento.');
 assert.equal(identificarMateria('Título: Teste\nAutor: Não informado\nRedação: Texto.').campos.autor,'');
 assert.throws(()=>identificarMateria('  '),/Cole o texto/);
 assert.throws(()=>identificarMateria('a'.repeat(120001)),/120 mil/);
 const corpo=identificarMateria('Redação: Corpo sem título.').campos;assert.equal(corpo.titulo,'');assert.equal(corpo.redacao,'Corpo sem título.');
});
test('revisão edita e inicia nova matéria sem salvar rascunhos ou executar atualização',async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
  const context=await browser.newContext({viewport:{width:1200,height:920}});
  let chamadas=0, rede=0;
  await context.route(/^https?:/, async route=>{rede++;await route.abort();});
  const p=await criarPainelManual(context,async()=>{chamadas++;});
  await p.getByRole('button',{name:'Adicionar matérias',exact:true}).click();
  await p.getByRole('button',{name:'Identificar campos',exact:true}).click();
  assert.match(await p.locator('#recado-entrada').textContent(),/Cole o texto/);
  await p.getByLabel('Texto recebido',{exact:true}).fill(exemplo);
  await p.screenshot({path:require('node:path').join(__dirname,'../work/adicionar-entrada.png')});
  await p.getByRole('button',{name:'Identificar campos',exact:true}).click();
  assert.equal(await p.locator('#revisao-materia').isVisible(),true);
  assert.equal(await p.locator('[data-campo=autor] .valor').textContent(),'Em branco');
  await p.getByRole('button',{name:'Alterar Autor',exact:true}).click();
  await p.getByRole('textbox',{name:'Autor',exact:true}).fill('Ana Souza');
  await p.getByRole('button',{name:'Aplicar',exact:true}).click();
  await p.getByRole('button',{name:'Alterar Título',exact:true}).click();
  await p.getByRole('textbox',{name:'Título',exact:true}).fill('Descartar esta mudança');
  await p.getByRole('button',{name:'Cancelar',exact:true}).click();
  assert.match(await p.locator('[data-campo=titulo] .valor').textContent(),/^Rio Largo/);
  await p.locator('#revisao-materia').evaluate(el=>{el.scrollTop=0;});
  await p.screenshot({path:require('node:path').join(__dirname,'../work/adicionar-revisao.png')});
  await p.getByRole('button',{name:'Fechar revisão',exact:true}).click();
  await p.getByRole('button',{name:'Adicionar matérias',exact:true}).click();
  await p.getByRole('button',{name:'Continuar revisão',exact:true}).click();
  assert.equal(await p.locator('[data-campo=autor] .valor').textContent(),'Ana Souza');
  await p.getByRole('button',{name:'Alterar Bigode',exact:true}).click();
  const html='<img src=x onerror="window.executou=true">';
  await p.getByRole('textbox',{name:'Bigode',exact:true}).fill(html);
  await p.getByRole('button',{name:'Fechar revisão',exact:true}).click();
  await p.getByRole('button',{name:'Adicionar matérias',exact:true}).click();
  await p.getByRole('button',{name:'Continuar revisão',exact:true}).click();
  assert.equal(await p.locator('[data-campo=bigode] .valor').textContent(),html);
  assert.equal(await p.evaluate(()=>Boolean(window.executou)),false);
  assert.equal(chamadas,0);assert.equal(rede,0);
  await p.setViewportSize({width:390,height:844});
  const box=await p.locator('#revisao-materia').boundingBox();assert.ok(box.x>=0 && box.x+box.width<=390);
  await p.getByRole('button',{name:'Alterar Autor',exact:true}).click();
  await p.getByRole('textbox',{name:'Autor',exact:true}).fill('Edição ainda aberta');
  await p.getByRole('button',{name:'Nova matéria',exact:true}).click();
  assert.equal(await p.getByLabel('Texto recebido',{exact:true}).inputValue(),'');
  assert.equal(await p.getByLabel('Texto recebido',{exact:true}).evaluate(el=>document.activeElement===el),true);
  assert.equal(await p.locator('#continuar-revisao').isVisible(),false);
  assert.equal(await p.locator('#campos-identificados').textContent(),'');
  await p.getByLabel('Texto recebido',{exact:true}).fill('Título: Segunda matéria\nRedação: Outro texto.');
  await p.getByRole('button',{name:'Identificar campos',exact:true}).click();
  assert.equal(await p.locator('[data-campo=titulo] .valor').textContent(),'Segunda matéria');
  assert.equal(await p.locator('[data-campo=autor] .valor').textContent(),'Em branco');
  assert.equal(await p.locator('[data-campo=bigode] .valor').textContent(),'Em branco');
  assert.equal(await p.evaluate(()=>localStorage.getItem('manual-materia-rascunho-v1')),null);
  await p.reload();
  await p.getByRole('button',{name:'Adicionar matérias',exact:true}).click();
  assert.equal(await p.getByLabel('Texto recebido',{exact:true}).inputValue(),'');
  assert.equal(await p.locator('#continuar-revisao').isVisible(),false);
  assert.equal(chamadas,0);assert.equal(rede,0);
 } finally {await browser.close();}
});
